<!DOCTYPE html>
<html lang="fr">
	<head>
		<title><?php echo $this->getTitle(); ?></title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-responsive.min.css">
		<link href="/css/main.css" rel="stylesheet">
		<?php echo $this->styles();?>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	</head>
	<body>
		<div id="container">
			<?php echo $this->getContent();?>
		</div> <!-- /container -->
	    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
	    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
		<?php echo $this->scripts();?>
	</body>
</html>